version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:1.3.7
    environment:
      - cluster.name="docker-cluster"
      - network.host=0.0.0.0
      - discovery.type=single-node
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx1g"
    ports:
      - "9200:9200"
